version: "3.8"

services:
  client:
    build: ./client
    container_name: clientapp_c
    ports:
      - "3002:3002"
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  contentcreator:
    build: ./contentcreator
    container_name: contentcreatorapp_c
    ports:
      - "3001:3001"
    volumes:
      - ./contentcreator:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  admin:
    build: ./admin
    container_name: adminapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./admin:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  api:
    build: ./api
    container_name: apiapp_c
    ports:
      - "8800:8800"
    volumes:
      - ./api:/app
      - ./app/node_modules
