name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  PORT: ${{ secrets.PORT }}
  CHAPA_AUTH_KEY: ${{ secrets.CHAPA_AUTH_KEY }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Admin Dependencies
        working-directory: ./admin
        run: npm install --legacy-peer-deps

      - name: Install Content Creator Dependencies
        working-directory: ./contentCreator
        run: npm install --legacy-peer-deps

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Install Server Dependencies
        working-directory: ./api
        run: npm install --legacy-peer-deps

      - name: Build Admin Docker Image
        working-directory: ./admin
        run: docker build -t adminapp .

      - name: Build ContentCreator Docker Image
        working-directory: ./contentCreator
        run: docker build -t contentcreatorapp .

      - name: Build Client Docker Image
        working-directory: ./client
        run: docker build -t clientapp .

      - name: Build Server Docker Image
        working-directory: ./api
        run: docker build -t serverapp .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker tag adminapp ephab/ethio-movie-app:admin-${{github.run_number}}
          docker tag contentcreatorapp ephab/ethio-movie-app:contentcreator-${{github.run_number}}
          docker tag clientapp ephab/ethio-movie-app:client-${{github.run_number}}
          docker tag serverapp ephab/ethio-movie-app:server-${{github.run_number}}
          docker push ephab/ethio-movie-app:admin-${{github.run_number}}
          docker push ephab/ethio-movie-app:contentcreator-${{github.run_number}}
          docker push ephab/ethio-movie-app:client-${{github.run_number}}
          docker push ephab/ethio-movie-app:server-${{github.run_number}}

      - name: Deploy Containers
        run: |
          docker run --name adminapp_c -p 3000:3000 -d ephab/ethio-movie-app:admin-${{github.run_number}}
          docker run --name contentcreatorapp_c -p 3001:3000 -d ephab/ethio-movie-app:contentcreator-${{github.run_number}}
          docker run --name clientapp_c -p 3002:3000 -d ephab/ethio-movie-app:client-${{github.run_number}}
          docker run --name serverapp_c -p 8800:8800 -d ephab/ethio-movie-app:server-${{github.run_number}}
